version: '3.8'

services:
  backend:
    build:
      context: ./lanchonete-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./lanchonete-backend/src/database:/app/src/database
    environment:
      - FLASK_ENV=development
    networks:
      - lanchonete-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000/api
    networks:
      - lanchonete-network

networks:
  lanchonete-network:
    driver: bridge

